"""
Seed the database with 2026 Uganda general election data.

Data sourced from official Electoral Commission declarations (Jan 17, 2026),
cross-referenced with Daily Monitor, New Vision, Al Jazeera, and NTV Uganda.
"""

from datetime import datetime

SEED_SOURCE = {
    "name": "Uganda Electoral Commission",
    "url": "https://www.ec.or.ug",
    "description": "Official 2026 general election results declared by the Electoral Commission on January 17, 2026",
    "content_hash": "seed_2026_v1",
    "last_scraped": datetime(2026, 1, 17, 18, 0, 0),
}

# 2026 Uganda General Election — January 15, 2026
# Declared by EC Chairman Justice Simon Byabakama on January 17, 2026
SEED_RESULTS = [
    # ── National Presidential Totals (all 8 candidates) ──────────────
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Yoweri Kaguta Museveni",
        "party": "NRM",
        "vote_count": 7946772,
        "percentage": 71.65,
        "total_valid_votes": 11090848,
        "is_winner": 1,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Robert Kyagulanyi Ssentamu",
        "party": "NUP",
        "vote_count": 2741238,
        "percentage": 24.72,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "James Nathan Nandala Mafabi",
        "party": "FDC",
        "vote_count": 209039,
        "percentage": 1.88,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Gregory Mugisha Muntu Oyera",
        "party": "ANT",
        "vote_count": 59276,
        "percentage": 0.53,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Frank Bulira Kabinga",
        "party": "RPP",
        "vote_count": 45959,
        "percentage": 0.41,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Robert Kasibante",
        "party": "NPP",
        "vote_count": 33440,
        "percentage": 0.30,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Mubarak Munyagwa Sserunga",
        "party": "CMP",
        "vote_count": 31666,
        "percentage": 0.29,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Joseph Mabirizi",
        "party": "CP",
        "vote_count": 23458,
        "percentage": 0.21,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    # ── Parliamentary results (key constituencies with verified vote counts) ──
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Kampala Central",
        "constituency": "Kampala Central",
        "position": "Member of Parliament",
        "candidate_name": "Hajjat Minsa Kabanda",
        "party": "NRM",
        "vote_count": 22332,
        "percentage": 55.04,
        "total_valid_votes": 40574,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Kampala Central",
        "constituency": "Kampala Central",
        "position": "Member of Parliament",
        "candidate_name": "David Lewis Rubongoya",
        "party": "NUP",
        "vote_count": 18242,
        "percentage": 44.96,
        "total_valid_votes": 40574,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Nakawa",
        "constituency": "Nakawa West",
        "position": "Member of Parliament",
        "candidate_name": "Joel Ssenyonyi",
        "party": "NUP",
        "vote_count": 21765,
        "percentage": 69.42,
        "total_valid_votes": 31351,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Nakawa",
        "constituency": "Nakawa West",
        "position": "Member of Parliament",
        "candidate_name": "Anderson Burora",
        "party": "NRM",
        "vote_count": 9586,
        "percentage": 30.58,
        "total_valid_votes": 31351,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Fort Portal",
        "constituency": "Fort Portal City Central",
        "position": "Member of Parliament",
        "candidate_name": "Ronald Muhenda",
        "party": "Independent",
        "vote_count": 10831,
        "percentage": 59.23,
        "total_valid_votes": 18290,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Fort Portal",
        "constituency": "Fort Portal City Central",
        "position": "Member of Parliament",
        "candidate_name": "Alex Ruhunda",
        "party": "NRM",
        "vote_count": 7461,
        "percentage": 40.77,
        "total_valid_votes": 18290,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Obongi",
        "constituency": "Obongi County",
        "position": "Member of Parliament",
        "candidate_name": "Hassan Caps Fungaro",
        "party": "FDC",
        "vote_count": 8503,
        "percentage": 53.24,
        "total_valid_votes": 15973,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Jinja",
        "constituency": "Kagoma North",
        "position": "Member of Parliament",
        "candidate_name": "John Odwori",
        "party": "NUP",
        "vote_count": 9593,
        "percentage": 56.18,
        "total_valid_votes": 17074,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Mbarara",
        "constituency": "Mbarara City Woman",
        "position": "Woman Member of Parliament",
        "candidate_name": "Loyda Kyarikunda Twinomujuni",
        "party": "NRM",
        "vote_count": 31364,
        "percentage": 67.82,
        "total_valid_votes": 46244,
        "is_winner": 1,
    },
]
