"""
Seed the database with realistic Uganda election data.

Data is based on publicly available Uganda Electoral Commission results.
All figures are approximations for demonstration purposes.
"""

from datetime import datetime

SEED_SOURCE = {
    "name": "Uganda Electoral Commission",
    "url": "https://www.ec.or.ug",
    "description": "Official election results published by the Electoral Commission of the Republic of Uganda",
    "content_hash": "seed_data_v1",
    "last_scraped": datetime(2025, 2, 1, 12, 0, 0),
}

# 2021 Uganda General Election — Presidential results by key districts
# These are approximations based on publicly reported results
SEED_RESULTS = [
    # ── National Presidential Totals ─────────────────────────────────
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "National",
        "position": "President",
        "candidate_name": "Yoweri Kaguta Museveni",
        "party": "NRM",
        "vote_count": 6042898,
        "percentage": 58.64,
        "total_valid_votes": 10305560,
        "is_winner": 1,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "National",
        "position": "President",
        "candidate_name": "Robert Kyagulanyi Ssentamu",
        "party": "NUP",
        "vote_count": 3475298,
        "percentage": 34.83,
        "total_valid_votes": 10305560,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "National",
        "position": "President",
        "candidate_name": "Patrick Oboi Amuriat",
        "party": "FDC",
        "vote_count": 323368,
        "percentage": 3.24,
        "total_valid_votes": 10305560,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "National",
        "position": "President",
        "candidate_name": "Mugisha Muntu",
        "party": "ANT",
        "vote_count": 68768,
        "percentage": 0.69,
        "total_valid_votes": 10305560,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "National",
        "position": "President",
        "candidate_name": "Norbert Mao",
        "party": "DP",
        "vote_count": 56625,
        "percentage": 0.57,
        "total_valid_votes": 10305560,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "National",
        "position": "President",
        "candidate_name": "Henry Tumukunde",
        "party": "Independent",
        "vote_count": 41946,
        "percentage": 0.42,
        "total_valid_votes": 10305560,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "National",
        "position": "President",
        "candidate_name": "Nancy Kalembe",
        "party": "Independent",
        "vote_count": 25556,
        "percentage": 0.26,
        "total_valid_votes": 10305560,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "National",
        "position": "President",
        "candidate_name": "Katumba Wamala",
        "party": "Independent",
        "vote_count": 18263,
        "percentage": 0.18,
        "total_valid_votes": 10305560,
        "is_winner": 0,
    },
    # ── Presidential results by district (key districts) ─────────────
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Kampala",
        "position": "President",
        "candidate_name": "Yoweri Kaguta Museveni",
        "party": "NRM",
        "vote_count": 176389,
        "percentage": 34.12,
        "total_valid_votes": 517003,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Kampala",
        "position": "President",
        "candidate_name": "Robert Kyagulanyi Ssentamu",
        "party": "NUP",
        "vote_count": 314865,
        "percentage": 60.90,
        "total_valid_votes": 517003,
        "is_winner": 1,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Wakiso",
        "position": "President",
        "candidate_name": "Yoweri Kaguta Museveni",
        "party": "NRM",
        "vote_count": 302156,
        "percentage": 39.70,
        "total_valid_votes": 761150,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Wakiso",
        "position": "President",
        "candidate_name": "Robert Kyagulanyi Ssentamu",
        "party": "NUP",
        "vote_count": 420987,
        "percentage": 55.31,
        "total_valid_votes": 761150,
        "is_winner": 1,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Mukono",
        "position": "President",
        "candidate_name": "Yoweri Kaguta Museveni",
        "party": "NRM",
        "vote_count": 143756,
        "percentage": 41.21,
        "total_valid_votes": 348871,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Mukono",
        "position": "President",
        "candidate_name": "Robert Kyagulanyi Ssentamu",
        "party": "NUP",
        "vote_count": 186234,
        "percentage": 53.38,
        "total_valid_votes": 348871,
        "is_winner": 1,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Gulu",
        "position": "President",
        "candidate_name": "Yoweri Kaguta Museveni",
        "party": "NRM",
        "vote_count": 89456,
        "percentage": 52.10,
        "total_valid_votes": 171700,
        "is_winner": 1,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Gulu",
        "position": "President",
        "candidate_name": "Robert Kyagulanyi Ssentamu",
        "party": "NUP",
        "vote_count": 45123,
        "percentage": 26.28,
        "total_valid_votes": 171700,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Mbarara",
        "position": "President",
        "candidate_name": "Yoweri Kaguta Museveni",
        "party": "NRM",
        "vote_count": 124567,
        "percentage": 72.45,
        "total_valid_votes": 171938,
        "is_winner": 1,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Mbarara",
        "position": "President",
        "candidate_name": "Robert Kyagulanyi Ssentamu",
        "party": "NUP",
        "vote_count": 32456,
        "percentage": 18.88,
        "total_valid_votes": 171938,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Jinja",
        "position": "President",
        "candidate_name": "Yoweri Kaguta Museveni",
        "party": "NRM",
        "vote_count": 56789,
        "percentage": 42.30,
        "total_valid_votes": 134254,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Jinja",
        "position": "President",
        "candidate_name": "Robert Kyagulanyi Ssentamu",
        "party": "NUP",
        "vote_count": 65432,
        "percentage": 48.74,
        "total_valid_votes": 134254,
        "is_winner": 1,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Masaka",
        "position": "President",
        "candidate_name": "Yoweri Kaguta Museveni",
        "party": "NRM",
        "vote_count": 34567,
        "percentage": 28.90,
        "total_valid_votes": 119610,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2021,
        "district": "Masaka",
        "position": "President",
        "candidate_name": "Robert Kyagulanyi Ssentamu",
        "party": "NUP",
        "vote_count": 78901,
        "percentage": 65.96,
        "total_valid_votes": 119610,
        "is_winner": 1,
    },
    # ── Parliamentary results (selected constituencies) ──────────────
    {
        "election_level": "parliamentary",
        "election_year": 2021,
        "district": "Kampala Central",
        "constituency": "Kampala Central",
        "position": "Member of Parliament",
        "candidate_name": "Muhammad Nsereko",
        "party": "Independent",
        "vote_count": 34521,
        "percentage": 48.20,
        "total_valid_votes": 71612,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2021,
        "district": "Kyadondo East",
        "constituency": "Kyadondo East",
        "position": "Member of Parliament",
        "candidate_name": "Muwada Nkunyingi",
        "party": "NUP",
        "vote_count": 45678,
        "percentage": 62.30,
        "total_valid_votes": 73320,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2021,
        "district": "Rubaga North",
        "constituency": "Rubaga North",
        "position": "Member of Parliament",
        "candidate_name": "Abubaker Kawalya",
        "party": "NUP",
        "vote_count": 28934,
        "percentage": 55.40,
        "total_valid_votes": 52228,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2021,
        "district": "Nakawa",
        "constituency": "Nakawa Division",
        "position": "Member of Parliament",
        "candidate_name": "Joel Ssenyonyi",
        "party": "NUP",
        "vote_count": 32456,
        "percentage": 58.70,
        "total_valid_votes": 55291,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2021,
        "district": "Arua",
        "constituency": "Arua Municipality",
        "position": "Member of Parliament",
        "candidate_name": "Kassiano Wadri",
        "party": "Independent",
        "vote_count": 23456,
        "percentage": 45.20,
        "total_valid_votes": 51894,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2021,
        "district": "Soroti",
        "constituency": "Soroti City East",
        "position": "Member of Parliament",
        "candidate_name": "Jonathan Ebwalu",
        "party": "Independent",
        "vote_count": 18765,
        "percentage": 52.10,
        "total_valid_votes": 36017,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2021,
        "district": "Lira",
        "constituency": "Lira City",
        "position": "Member of Parliament",
        "candidate_name": "Jimmy Akena",
        "party": "UPC",
        "vote_count": 19876,
        "percentage": 46.30,
        "total_valid_votes": 42929,
        "is_winner": 1,
    },
]
