"""
Seed the database with 2026 Uganda general election data.

Data sourced from official Electoral Commission declarations and Form DR
documents posted on the EC's X account (@UgandaEC).

Sources and SHA-256 content hashes:
  - Presidential national totals: EC declaration Jan 17, 2026
  - Parliamentary results: EC declaration Jan 17, 2026
  - UPDF Males (Form DR, 28 Jan 2026):
    sha256: 7fe3200d2eb199b0f65fed3e300e555ba966738dfd120f789c459513e78a0b42
  - UPDF Females (Form DR, 28 Jan 2026):
    sha256: 57a88cba186370e28f5c1d5679b13ce3c9badf749c6b17ea8dc2b94902fe9438
"""

from datetime import datetime

SEED_SOURCE = {
    "name": "Uganda Electoral Commission",
    "url": "https://www.ec.or.ug",
    "description": "Official 2026 general election results declared by the Electoral Commission on January 17, 2026",
    "content_hash": "seed_2026_v2",
    "last_scraped": datetime(2026, 1, 17, 18, 0, 0),
}

# 2026 Uganda General Election — January 15, 2026
# Declared by EC Chairman Justice Simon Byabakama on January 17, 2026
SEED_RESULTS = [
    # ── National Presidential Totals (all 8 candidates) ──────────────
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Yoweri Kaguta Museveni",
        "party": "NRM",
        "vote_count": 7946772,
        "percentage": 71.65,
        "total_valid_votes": 11090848,
        "is_winner": 1,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Robert Kyagulanyi Ssentamu",
        "party": "NUP",
        "vote_count": 2741238,
        "percentage": 24.72,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "James Nathan Nandala Mafabi",
        "party": "FDC",
        "vote_count": 209039,
        "percentage": 1.88,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Gregory Mugisha Muntu Oyera",
        "party": "ANT",
        "vote_count": 59276,
        "percentage": 0.53,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Frank Bulira Kabinga",
        "party": "RPP",
        "vote_count": 45959,
        "percentage": 0.41,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Robert Kasibante",
        "party": "NPP",
        "vote_count": 33440,
        "percentage": 0.30,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Mubarak Munyagwa Sserunga",
        "party": "CMP",
        "vote_count": 31666,
        "percentage": 0.29,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    {
        "election_level": "presidential",
        "election_year": 2026,
        "district": "National",
        "position": "President",
        "candidate_name": "Joseph Mabirizi",
        "party": "CP",
        "vote_count": 23458,
        "percentage": 0.21,
        "total_valid_votes": 11090848,
        "is_winner": 0,
    },
    # ── Parliamentary results (key constituencies with verified vote counts) ──
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Kampala Central",
        "constituency": "Kampala Central",
        "position": "Member of Parliament",
        "candidate_name": "Hajjat Minsa Kabanda",
        "party": "NRM",
        "vote_count": 22332,
        "percentage": 55.04,
        "total_valid_votes": 40574,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Kampala Central",
        "constituency": "Kampala Central",
        "position": "Member of Parliament",
        "candidate_name": "David Lewis Rubongoya",
        "party": "NUP",
        "vote_count": 18242,
        "percentage": 44.96,
        "total_valid_votes": 40574,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Nakawa",
        "constituency": "Nakawa West",
        "position": "Member of Parliament",
        "candidate_name": "Joel Ssenyonyi",
        "party": "NUP",
        "vote_count": 21765,
        "percentage": 69.42,
        "total_valid_votes": 31351,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Nakawa",
        "constituency": "Nakawa West",
        "position": "Member of Parliament",
        "candidate_name": "Anderson Burora",
        "party": "NRM",
        "vote_count": 9586,
        "percentage": 30.58,
        "total_valid_votes": 31351,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Fort Portal",
        "constituency": "Fort Portal City Central",
        "position": "Member of Parliament",
        "candidate_name": "Ronald Muhenda",
        "party": "Independent",
        "vote_count": 10831,
        "percentage": 59.23,
        "total_valid_votes": 18290,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Fort Portal",
        "constituency": "Fort Portal City Central",
        "position": "Member of Parliament",
        "candidate_name": "Alex Ruhunda",
        "party": "NRM",
        "vote_count": 7461,
        "percentage": 40.77,
        "total_valid_votes": 18290,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Obongi",
        "constituency": "Obongi County",
        "position": "Member of Parliament",
        "candidate_name": "Hassan Caps Fungaro",
        "party": "FDC",
        "vote_count": 8503,
        "percentage": 53.24,
        "total_valid_votes": 15973,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Jinja",
        "constituency": "Kagoma North",
        "position": "Member of Parliament",
        "candidate_name": "John Odwori",
        "party": "NUP",
        "vote_count": 9593,
        "percentage": 56.18,
        "total_valid_votes": 17074,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "Mbarara",
        "constituency": "Mbarara City Woman",
        "position": "Woman Member of Parliament",
        "candidate_name": "Loyda Kyarikunda Twinomujuni",
        "party": "NRM",
        "vote_count": 31364,
        "percentage": 67.82,
        "total_valid_votes": 46244,
        "is_winner": 1,
    },
    # ── UPDF Males Representatives to Parliament ─────────────────────
    # Form DR declared by Returning Officer Kateeba Tumusiime Diana
    # 28 Jan 2026, Land Forces Headquarters, Bombo
    # SHA-256: 7fe3200d2eb199b0f65fed3e300e555ba966738dfd120f789c459513e78a0b42
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "UPDF",
        "constituency": "UPDF Males",
        "position": "UPDF Male Representative to Parliament",
        "candidate_name": "Okidling SAM",
        "party": "UPDF",
        "vote_count": 340,
        "percentage": 18.08,
        "total_valid_votes": 1881,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "UPDF",
        "constituency": "UPDF Males",
        "position": "UPDF Male Representative to Parliament",
        "candidate_name": "Mugira James",
        "party": "UPDF",
        "vote_count": 303,
        "percentage": 16.11,
        "total_valid_votes": 1881,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "UPDF",
        "constituency": "UPDF Males",
        "position": "UPDF Male Representative to Parliament",
        "candidate_name": "Kavuma Samuel",
        "party": "UPDF",
        "vote_count": 282,
        "percentage": 14.99,
        "total_valid_votes": 1881,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "UPDF",
        "constituency": "UPDF Males",
        "position": "UPDF Male Representative to Parliament",
        "candidate_name": "Gonyi David Robert",
        "party": "UPDF",
        "vote_count": 266,
        "percentage": 14.14,
        "total_valid_votes": 1881,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "UPDF",
        "constituency": "UPDF Males",
        "position": "UPDF Male Representative to Parliament",
        "candidate_name": "Masiko Henry Moses",
        "party": "UPDF",
        "vote_count": 251,
        "percentage": 13.34,
        "total_valid_votes": 1881,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "UPDF",
        "constituency": "UPDF Males",
        "position": "UPDF Male Representative to Parliament",
        "candidate_name": "Kinalwa James",
        "party": "UPDF",
        "vote_count": 241,
        "percentage": 12.81,
        "total_valid_votes": 1881,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "UPDF",
        "constituency": "UPDF Males",
        "position": "UPDF Male Representative to Parliament",
        "candidate_name": "Ssemwanga Joseph",
        "party": "UPDF",
        "vote_count": 198,
        "percentage": 10.53,
        "total_valid_votes": 1881,
        "is_winner": 0,
    },
    # ── UPDF Females Representatives to Parliament ───────────────────
    # Form DR declared by Returning Officer Kateeba Tumusiime Diana
    # 28 Jan 2026, Land Forces Headquarters, Bombo
    # SHA-256: 57a88cba186370e28f5c1d5679b13ce3c9badf749c6b17ea8dc2b94902fe9438
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "UPDF",
        "constituency": "UPDF Females",
        "position": "UPDF Female Representative to Parliament",
        "candidate_name": "Meeme Sylivia",
        "party": "UPDF",
        "vote_count": 314,
        "percentage": 35.60,
        "total_valid_votes": 882,
        "is_winner": 1,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "UPDF",
        "constituency": "UPDF Females",
        "position": "UPDF Female Representative to Parliament",
        "candidate_name": "Ikiriza Knight",
        "party": "UPDF",
        "vote_count": 307,
        "percentage": 34.81,
        "total_valid_votes": 882,
        "is_winner": 0,
    },
    {
        "election_level": "parliamentary",
        "election_year": 2026,
        "district": "UPDF",
        "constituency": "UPDF Females",
        "position": "UPDF Female Representative to Parliament",
        "candidate_name": "Nekesa Christine Situma",
        "party": "UPDF",
        "vote_count": 261,
        "percentage": 29.59,
        "total_valid_votes": 882,
        "is_winner": 0,
    },
]
